# Generated by Django 5.2.7 on 2025-11-30 14:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('idAnggota', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('noWA', models.CharField(max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tanggalStart', models.DateField()),
                ('tanggalEnd', models.DateField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('non-aktif', 'Non-Aktif')], max_length=10)),
                ('jenisSampah', models.CharField(choices=[('Rumah Tangga', 'Rumah Tangga'), ('Tempat Usaha', 'Tempat Usaha')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('idTamu', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimPengangkut',
            fields=[
                ('idTim', models.AutoField(primary_key=True, serialize=False)),
                ('namaTim', models.CharField(max_length=100)),
                ('noWhatsapp', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('anggota', 'Anggota'), ('tim_angkut', 'Tim Angkut'), ('tamu', 'Tamu'), ('admin', 'Admin')], default='tamu', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LaporanSampah',
            fields=[
                ('idLaporan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lapor', models.DateField()),
                ('alamat', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('deskripsi', models.TextField()),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to='laporan_fotos/', verbose_name='Foto Bukti')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('idAnggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.anggota')),
            ],
            options={
                'db_table': 'laporan_sampah',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('idPembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalBayar', models.DateField()),
                ('jumlahBayar', models.IntegerField()),
                ('metodeBayar', models.CharField(max_length=50)),
                ('statusBayar', models.CharField(choices=[('pending', 'Pending'), ('lunas', 'Lunas'), ('gagal', 'Gagal')], default='pending', max_length=10)),
                ('buktiBayar', models.BinaryField()),
                ('idAnggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.anggota')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('idJadwal', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalJadwal', models.DateField()),
                ('idTim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.timpengangkut')),
            ],
        ),
        migrations.CreateModel(
            name='DetailAnggotaJadwal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_pengangkutan', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('dalam_proses', 'Dalam Proses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='terjadwal', max_length=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idAnggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.anggota')),
                ('idJadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.jadwal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idAnggota', 'idJadwal'), name='unique_anggota_jadwal')],
            },
        ),
    ]
