# Generated by Django 5.2.7 on 2025-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_anggota_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansampah',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laporansampah',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
