# Generated by Django 5.2.7 on 2025-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0003_alter_laporansampah_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansampah',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='laporansampah',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
    ]
