# Generated by Django 5.2.8 on 2025-12-02 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_alter_laporansampah_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporansampah',
            name='idAnggota',
        ),
        migrations.AddField(
            model_name='laporansampah',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_sampah', to=settings.AUTH_USER_MODEL),
        ),
    ]
