# Generated by Django 5.2.8 on 2025-12-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_remove_laporansampah_idanggota_laporansampah_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
