# Generated by Django 5.2.8 on 2025-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_tamu_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='buktiBayar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
