# Generated by Django 5.2.8 on 2025-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0008_alter_pembayaran_buktibayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='buktiBayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/', verbose_name='Bukti Pembayaran'),
        ),
    ]
