# Generated by Django 5.2.7 on 2025-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0010_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('endpoint',), name='unique_push_subscription_endpoint'),
        ),
    ]
