# Generated by Django 5.2.7 on 2025-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Tujuan'),
        ),
    ]
