# Generated by Django 5.2.7 on 2026-01-02 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0014_alter_tamu_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='timpengangkut',
            name='idUser',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
