# Generated by Django 5.2.7 on 2026-01-02 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0015_timpengangkut_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timpengangkut',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
