# Generated by Django 5.2.7 on 2026-01-02 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0016_alter_timpengangkut_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansampah',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_sampah', to=settings.AUTH_USER_MODEL),
        ),
    ]
