# Generated by Django 5.2.7 on 2026-01-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0017_alter_laporansampah_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansampah',
            name='tanggal_lapor',
            field=models.DateField(auto_now_add=True),
        ),
    ]
