# Generated by Django 5.2.7 on 2026-01-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0018_alter_laporansampah_tanggal_lapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansampah',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laporansampah',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
